site_name: RFID-activated lockbox documentation
theme:
  name: readthedocs

plugins:
    - glightbox # This plugin enables the image lightbox

nav:
    - Home: index.md
    - Electronic:
      - rfid.md
      - lcd.md
      - servo.md
      - led_strip.md
    - Mechanical:
      - cad.md
